name: First Github Workflow

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha}}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment

on:
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo This is the first step of my first job.

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -Dtest=CloudAppApplicationTest test
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/ami.pkr.hcl"